name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Cambié esto para que se ejecute en horarios específicos

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
      pages: write  # Agregado
      id-token: write  # Agregado
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Aumenté el timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Agregado checkout

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4  # Actualicé la versión
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
